[project]
name = 'onloan'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-deposit'

[contracts.sip-010-trait-v2]
path = 'contracts/traits/sip-010-trait-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.oracle-trait-v2]
path = 'contracts/traits/oracle-trait-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.pool-trait-v2]
path = 'contracts/traits/pool-trait-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.usdcx]
path = 'contracts/usdcx.clar'
clarity_version = 4
epoch = 'latest'

[contracts.onloan-core-v2]
path = 'contracts/onloan-core-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.pyth-oracle-adapter-v2]
path = 'contracts/pyth-oracle-adapter-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.lending-pool-v2]
path = 'contracts/lending-pool-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.collateral-manager-v2]
path = 'contracts/collateral-manager-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.liquidation-engine-v2]
path = 'contracts/liquidation-engine-v2.clar'
clarity_version = 4
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'


